### ISSUE TITLE
Add options?

### ISSUE THREAD

**Issue by DaveAtDog** [sindresorhus/strip-debug#10]
It'd be great if you could pass options to strip-debug. In my use case I need the alert() call to remain in the production code.

e.g: stripDebug(['console','debugger']) would leave the alerts in place.

**Comment by sindresorhus** [comment]
Already answered in other issues. Not interested in options. If you use alert() in production, you're doing it wrong.

**Comment by DaveAtDog** [comment]
I'm now re-thinking how to implement my alerts but in the short term I've tweaked your otherwise very useful script thusly: // stripAlert(node); ;)

Cheers, Dave

**Comment by sindresorhus** [comment]
You should use inline/context notifications. `alert()` has a LOT of downsides: http://stackoverflow.com/a/8825479/64949

**Comment by anrananran** [comment]
you are too extreme because alert can be rewrite, an option is necessary.

**Comment by anrananran** [comment]
@sindresorhus  alert can be rewrite, an option is necessary.
