### ISSUE TITLE
Problems when reading input from stdin

### ISSUE THREAD

**Issue by gianlucacandiotti** [sindresorhus/strip-debug#15]
Hi!

I have a problem when piping the output from uglify into strip-debug. It works fine if I make it read from the file generated by uglify though. It throws this error.

<img width="889" alt="screen shot 2017-09-22 at 15 21 03" src="https://user-images.githubusercontent.com/7819696/30762939-b13fadd4-9fa9-11e7-94f0-a9dad1e3bd40.png">

The error points to a function called getStdin at cli.js. It looks like this.

<img width="383" alt="screen shot 2017-09-22 at 15 23 03" src="https://user-images.githubusercontent.com/7819696/30763017-fa40d184-9fa9-11e7-9b28-5436b5765f4e.png">

It looked weird since it wasn't reading the data argument. If you call strip with the data argument instead of input it works fine. I'm just not sure if having input is necessary in there for other things to work.

If it's the only necessary change I could make a pr.

Thanks!

**Comment by kevva** [comment]
Definitely a bug, but it was fixed in https://github.com/sindresorhus/strip-debug/commit/0f8143c7b5cb3ba83ad7358b38275c7c10962fa6. Needs a version bump though @sindresorhus.

**Comment by sindresorhus** [comment]
Done. I moved the CLI out into a separate package: https://github.com/sindresorhus/strip-debug-cli

**Comment by gianlucacandiotti** [comment]
Thanks! Appreciate the quick response. 👍
