### ISSUE TITLE
Convert to Babel plugin

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/strip-debug#20]
[<img alt="Issuehunt badges" src="https://issuehunt.io/r/sindresorhus/strip-debug/issues/20/badge.svg" />](https://issuehunt.io/r/sindresorhus/strip-debug/issues/20)

Rocambole, which this project is built on, is no longer maintained.

Would be best to convert this project to a Babel plugin. Then we also get #11 for free.

> There is a $80.00 open bounty on this issue. Add more on [Issuehunt](https://issuehunt.io/r/sindresorhus/strip-debug/issues/20).
> - Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/strip-debug/) to discover more funded issues.
> - Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on Issuehunt to raise funds.

**Comment by alexzherdev** [comment]
It looks like babel-minify contains plugins to remove [`console`](https://github.com/babel/minify/tree/master/packages/babel-plugin-transform-remove-console) and [`debugger`](https://github.com/babel/minify/tree/master/packages/babel-plugin-transform-remove-debugger). For `alert` I found [this one](https://github.com/azu/babel-plugin-strip-function-call) although not sure if it'd have to be updated for Babel 7.

**Comment by sindresorhus** [comment]
If anyone wants to work on this, see the previous attempt and the feedback there: https://github.com/sindresorhus/strip-debug/pull/21 Probably worth just continuing from there.
